const MEMORIES = [
  { year: '2020', event: 'Премия Хрустальная пирамида', src: 'photos/photo-01.jpg', left: '7%', top: '0%', rot: '-12deg' },
  { year: '2021', event: 'Гран-При Ростелеком', src: 'photos/photo-02.jpg', left: '10%', top: '11%', rot: '8deg' },
  { year: '2021', event: 'Гран-При Ростелеком', src: 'photos/photo-03.jpg', left: '40%', top: '4%', rot: '-5deg' },
  { year: '2021', event: 'Гран-При Ростелеком', src: 'photos/photo-04.jpg', left: '45%', top: '0%', rot: '14deg' },
  { year: '2021', event: 'Кулинарный тимбилдинг', src: 'photos/photo-05.jpg', left: '68%', top: '8%', rot: '-9deg' },
  { year: '2021', event: 'Поездка в Мурманск', src: 'photos/photo-06.jpg', left: '0%', top: '21%', rot: '6deg' },
  { year: '2021', event: 'Поездка в Мурманск', src: 'photos/photo-07.jpg', left: '20%', top: '8%', rot: '-15deg' },
  { year: '2021', event: 'Программа Директор и команда', src: 'photos/photo-08.jpg', left: '42%', top: '14%', rot: '4deg' },
  { year: '2022', event: 'Кино в Художественном', src: 'photos/photo-09.jpg', left: '38%', top: '18%', rot: '11deg' },
  { year: '2022', event: 'Новогодний корпоратив', src: 'photos/photo-10.jpg', left: '68%', top: '4%', rot: '-7deg' },
  { year: '2023', event: 'Премия Признание', src: 'photos/photo-11.jpg', left: '2%', top: '25%', rot: '9deg' },
  { year: '2023', event: 'Премия Эффективное образование', src: 'photos/photo-12.jpg', left: '26%', top: '19%', rot: '-3deg' },
  { year: '2023', event: 'Премия Эффективное образование', src: 'photos/photo-13.jpg', left: '26%', top: '31%', rot: '13deg' },
  { year: '2023', event: 'Собрались в бар', src: 'photos/photo-14.jpg', left: '51%', top: '16%', rot: '-10deg' },
  { year: '2024-25', event: 'Новогодний корпоратив', src: 'photos/photo-15.jpg', left: '68%', top: '24%', rot: '2deg' },
  { year: '2024-25', event: 'Новогодний корпоратив', src: 'photos/photo-16.jpg', left: '0%', top: '21%', rot: '-8deg' },
  { year: '2024-25', event: 'Новогодний корпоратив', src: 'photos/photo-17.jpg', left: '19%', top: '37%', rot: '12deg' },
  { year: '2024-25', event: 'Новогодний корпоратив', src: 'photos/photo-18.jpg', left: '24%', top: '30%', rot: '-4deg' },
  { year: '2025', event: 'Поездка в Суздаль', src: 'photos/photo-19.jpg', left: '54%', top: '24%', rot: '7deg' },
  { year: '2025', event: 'Поездка в Суздаль', src: 'photos/photo-20.jpg', left: '61%', top: '38%', rot: '-14deg' },
  { year: '2025', event: 'Премия Team Awards', src: 'photos/photo-21.jpg', left: '13%', top: '41%', rot: '3deg' },
  { year: '', event: 'Первый запуск Школы 21', src: 'photos/photo-22.jpg', left: '14%', top: '29%', rot: '-11deg' },
  { year: '', event: 'Самый первый HR-синк', src: 'photos/photo-23.jpg', left: '33%', top: '44%', rot: '10deg' },
  { year: '', event: 'Стратсессия ИТ', src: 'photos/photo-24.jpg', left: '55%', top: '38%', rot: '-2deg' },
  { year: '', event: 'Итоги года у ГВ', src: 'photos/photo-25.jpg', left: '52%', top: '48%', rot: '15deg' },
  { year: '', event: 'Итоги года у ГВ', src: 'photos/photo-26.jpg', left: '6%', top: '44%', rot: '-6deg' },
  { year: '', event: 'Итоги года у ГВ', src: 'photos/photo-27.jpg', left: '10%', top: '54%', rot: '5deg' },
  { year: '', event: 'Когда-то в офисе', src: 'photos/photo-28.jpg', left: '38%', top: '49%', rot: '-13deg' },
  { year: '', event: '', src: 'photos/photo-29.jpg', left: '42%', top: '41%', rot: '1deg' },
  { year: '', event: '', src: 'photos/photo-30.jpg', left: '65%', top: '52%', rot: '-8deg' },
];
